version: '3.8'

services:
  app:
    image: node:22-alpine3.19
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "3001:3001"
    command: >
      sh -c "npm install --only=development && npm start"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
